# Generated by Django 5.0.7 on 2024-08-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='media')),
                ('desc', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('whatsapp', models.TextField(max_length=1000)),
                ('github', models.TextField(max_length=1000)),
            ],
        ),
    ]
