# Generated by Django 5.0.7 on 2024-08-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_equipe_desc_equipe_fonction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='partenaire',
            name='email',
        ),
    ]
