# Generated by Django 5.0.7 on 2024-08-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_partenaire_desc_remove_partenaire_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='nom',
            field=models.URLField(help_text="Entrez l'URL du site web"),
        ),
    ]
