# Generated by Django 5.0.7 on 2024-08-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_partenaire_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, default='inconnue', max_length=100, null=True),
        ),
    ]
