# Generated by Django 5.0.7 on 2024-09-03 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_academie_bitcoin_immobilier_informatique_laboratoire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_Audio_Visuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=1000, unique=True)),
                ('description', models.TextField()),
                ('image_entete', models.ImageField(upload_to='media/production')),
                ('image1', models.ImageField(upload_to='media/production')),
                ('image2', models.ImageField(upload_to='media/production')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('youtube_url', models.URLField(help_text="Entrez l'URL de youtube", max_length=2000)),
                ('podcast_url', models.URLField(help_text="Entrez l'URL du site web", max_length=2000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
