# Generated by Django 5.0.7 on 2024-09-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_production_audio_visuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='academie',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/academie', verbose_name='Academie'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/bitcoin', verbose_name='Bitcoin'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='immobilier',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/immobilier', verbose_name='Immobilier'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='informatique',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/info', verbose_name='Informatique'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/labo', verbose_name='Laboratoire'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='production_audio_visuelle',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/production', verbose_name='Production'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='production_audio_visuelle',
            name='podcast_url',
            field=models.URLField(help_text="Entrez l'URL des podcasts", max_length=2000),
        ),
    ]
