# Generated by Django 5.0.7 on 2024-09-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_academie_catalogue_bitcoin_catalogue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academie',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/academie', verbose_name='Academie_catalogue'),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/bitcoin', verbose_name='Bitcoin_catalogue'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/immobilier', verbose_name='Immobilier_catalogue'),
        ),
        migrations.AlterField(
            model_name='informatique',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/info', verbose_name='Informatique_catalogue'),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/labo', verbose_name='Laboratoire_catalogue'),
        ),
        migrations.AlterField(
            model_name='production_audio_visuelle',
            name='catalogue',
            field=models.FileField(blank='True', null='True', upload_to='media/production', verbose_name='Production_catalogue'),
        ),
    ]
