# Generated by Django 5.0.7 on 2024-09-03 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_academie_catalogue_alter_bitcoin_catalogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='kiveclair_url',
            field=models.URLField(default=datetime.datetime(2024, 9, 3, 11, 51, 9, 449676, tzinfo=datetime.timezone.utc), help_text="Entrez l'URL de kiveclair", max_length=2000),
            preserve_default=False,
        ),
    ]
