# Generated by Django 5.0.7 on 2024-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bitcoin_kiveclair_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='whatsapp',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='equipe',
            name='tweeter',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
