# Generated by Django 5.0.7 on 2024-09-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_whatsapp_equipe_linkedin_equipe_tweeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
