# Generated by Django 5.0.7 on 2024-09-08 18:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contact_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academie',
            name='catalogue',
            field=models.FileField(blank='True', null='True', storage=django.core.files.storage.FileSystemStorage(location='media/uploads/'), upload_to='media/academie', verbose_name='Academie_catalogue'),
        ),
    ]
