# Generated by Django 5.0.7 on 2024-09-11 06:49

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_academie_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academie',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
