# Generated by Django 5.0.7 on 2024-09-13 05:56

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_academie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bitcoin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='immobilier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='informatique',
            name='description',
        ),
        migrations.RemoveField(
            model_name='laboratoire',
            name='description',
        ),
        migrations.RemoveField(
            model_name='production_audio_visuelle',
            name='description',
        ),
        migrations.AddField(
            model_name='academie',
            name='description1',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academie',
            name='description2',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academie',
            name='description3',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academie',
            name='description4',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academie',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/academie'),
        ),
        migrations.AddField(
            model_name='academie',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/academie'),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='description1',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='description2',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='description3',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='description4',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/bitcoin'),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/bitcoin'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='description1',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='description2',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='description3',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='description4',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/immobilier'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/immobilier'),
        ),
        migrations.AddField(
            model_name='informatique',
            name='description1',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informatique',
            name='description2',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informatique',
            name='description3',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informatique',
            name='description4',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informatique',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/info'),
        ),
        migrations.AddField(
            model_name='informatique',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/info'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='description1',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='description2',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='description3',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='description4',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/labo'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/labo'),
        ),
        migrations.AddField(
            model_name='production_audio_visuelle',
            name='description1',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_audio_visuelle',
            name='description2',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_audio_visuelle',
            name='description3',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_audio_visuelle',
            name='description4',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production_audio_visuelle',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/production'),
        ),
        migrations.AddField(
            model_name='production_audio_visuelle',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/production'),
        ),
        migrations.AlterField(
            model_name='academie',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/academie'),
        ),
        migrations.AlterField(
            model_name='academie',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/academie'),
        ),
        migrations.AlterField(
            model_name='academie',
            name='image_entete',
            field=models.ImageField(blank=True, null=True, upload_to='media/academie'),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/bitcoin'),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/bitcoin'),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='image_entete',
            field=models.ImageField(blank=True, null=True, upload_to='media/bitcoin'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/immobilier'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/immobilier'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='image_entete',
            field=models.ImageField(blank=True, null=True, upload_to='media/immobilier'),
        ),
        migrations.AlterField(
            model_name='informatique',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/info'),
        ),
        migrations.AlterField(
            model_name='informatique',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/info'),
        ),
        migrations.AlterField(
            model_name='informatique',
            name='image_entete',
            field=models.ImageField(blank=True, null=True, upload_to='media/info'),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/labo'),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/labo'),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='image_entete',
            field=models.ImageField(blank=True, null=True, upload_to='media/labo'),
        ),
        migrations.AlterField(
            model_name='production_audio_visuelle',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/production'),
        ),
        migrations.AlterField(
            model_name='production_audio_visuelle',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/production'),
        ),
        migrations.AlterField(
            model_name='production_audio_visuelle',
            name='image_entete',
            field=models.ImageField(blank=True, null=True, upload_to='media/production'),
        ),
    ]
