# Generated by Django 5.0.7 on 2024-09-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_email_contact_email1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email1',
            new_name='email',
        ),
    ]
